apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "$(INGRESS_FRONTEND_CONFIG_NAME)"
    kubernetes.io/ingress.global-static-ip-name: "dev-ai-dmsp"
  name: ai-dmsp-ingress
  labels:
    app.kubernetes.io/component: "ingress"
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ai-dmsp-api-service
                port:
                  number: 8081
      host: dmsp.dev.api.rtd.asu.edu
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ai-dmsp-react-service
                port:
                  number: 8080
      host: dmsp.dev.rtd.asu.edu
  tls:
    - secretName: ai-dmsp-tls
      hosts:
        - dmsp.dev.rtd.asu.edu
        - dmsp.dev.api.rtd.asu.edu
