steps:
  # Build the Docker image for test-dmsp-ai react
  - id: docker build react
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'Dockerfile.react',
        '-t',
        'gcr.io/$PROJECT_ID/test-dmsp-ai-react-image:$BUILD_ID',
        '--build-arg',
        'NPM_TOKEN=$$NPM_TOKEN',
        '.',
      ]
    secretEnv: ['NPM_TOKEN']
    env: ['DOCKER_BUILDKIT=1']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/dev-dmsp-ai-secret-npmrc-token/versions/latest
    env: 'NPM_TOKEN'
