apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ai-dmsp-api-hpa
spec:
  maxReplicas: 10
  scaleTargetRef:
    kind: Deployment
    name: ai-dmsp-api-deployment
    apiVersion: apps/v1
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ai-dmsp-react-hpa
spec:
  maxReplicas: 10
  scaleTargetRef:
    kind: Deployment
    name: ai-dmsp-react-deployment
    apiVersion: apps/v1
  targetCPUUtilizationPercentage: 50
